### PR TITLE
fix: make useRiveProperty setValue a no-op before instance is ready

### LINKED ISSUE #141: Commands called before Rive file/view is ready are dropped or fail (need internal queue/readiness gating)
### Problem
In `@rive-app/react-native` (Nitro), imperative commands can be called before the Rive view/file is fully ready.
This causes inconsistent behavior: commands may be ignored, fail, or throw depending on timing.

Affected calls include:
- play/pause/reset
- set/get state machine inputs (number/bool/trigger)
- set/get text run values

### Expected behavior
Calls made right after mount/configure should be deterministic:
- either queued and executed once view/file is ready
- or explicitly rejected in a documented, predictable way

### Actual behavior
Behavior is timing-dependent and flaky, especially on initial load/reload.
In real apps this appears as:
- first input updates not applied
- initial play/pause state not respected
- intermittent "not ready" style failures

### Reproduction (high level)
1. Mount a Rive component.
2. Immediately call input setters / play-pause (same tick or very early after mount).
3. Observe that some calls are lost or fail on first render, but succeed later.

### Platform
- iOS + Android
- React Native
- `@rive-app/react-native` 0.2.1 (Nitro)

### Notes
I implemented a local patch that defers/queues actions until view readiness and flushes once ready.
This resolves the flakiness in production usage.

### PR DESCRIPTION
**Pull request by mfazekas**
Fixes #141 (hooks level)

`useRiveProperty`'s `setValue` was throwing an error when called before the `ViewModelInstance` loaded. This is a common React pattern — `useEffect` fires on mount before async data is available.

Changed to silent no-op, as setValue does changes once the instance is available, no internal queue needed — React's dependency array handles it:

```tsx
const { setValue } = useRiveString('text', instance);

// setValue is in deps — React re-fires this effect when instance loads
// and setValue's identity changes (new property → new useCallback ref)
useEffect(() => {
  setValue('Hello');
}, [setValue]);
```

<details>
<summary>Reproducer</summary>

```tsx
import { useEffect, useMemo, useState } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import {
  RiveView,
  Fit,
  useRiveFile,
  useRive,
  useRiveString,
} from '@rive-app/react-native';

export default function Issue141Reproducer() {
  const { riveViewRef, setHybridRef } = useRive();
  const { riveFile, isLoading } = useRiveFile(
    require('./font_fallback.riv')
  );
  const instance = useMemo(
    () => riveFile?.defaultArtboardViewModel()?.createDefaultInstance(),
    [riveFile]
  );

  const {
    value: currentText,
    setValue: setText,
    error: textError,
  } = useRiveString('text', instance);

  const [errorLog, setErrorLog] = useState<string[]>([]);

  useEffect(() => {
    if (textError) {
      setErrorLog((prev) => [
        ...prev,
        `[${new Date().toLocaleTimeString()}] ${textError.message}`,
      ]);
    }
  }, [textError]);

  // This fires on mount before the file is loaded — triggers the error
  useEffect(() => {
    setText('Hello from useEffect');
    riveViewRef?.playIfNeeded();
  }, [setText, riveViewRef]);

  return (
    <View style={styles.container}>
      <View style={styles.info}>
        <Text style={styles.title}>Issue #141 — Hooks Level</Text>
        <Text style={styles.description}>
          setText() is called in a useEffect on mount. Since useRiveFile is
          async, instance is undefined on first render → useRiveString's
          setValue fires an error.
        </Text>
        <Text>Loading: {isLoading ? 'yes' : 'no'}</Text>
        <Text>Instance: {instance ? 'ready' : 'undefined'}</Text>
        <Text>Current text: {currentText ?? '(none)'}</Text>
        <Text style={textError && styles.errorText}>
          Error: {textError ? textError.message : '(none)'}
        </Text>
      </View>

      <View style={styles.riveContainer}>
        {riveFile && instance ? (
          <RiveView
            style={styles.rive}
            autoPlay
            dataBind={instance}
            fit={Fit.Contain}
            file={riveFile}
            hybridRef={setHybridRef}
          />
        ) : (
          <Text>{isLoading ? 'Loading...' : 'No file'}</Text>
        )}
      </View>

      <View style={styles.logContainer}>
        <Text style={styles.logTitle}>Error Log</Text>
        {errorLog.length === 0 ? (
          <Text style={styles.logPlaceholder}>No errors recorded</Text>
        ) : (
          errorLog.map((entry, i) => (
            <Text key={i} style={styles.logEntry}>{entry}</Text>
          ))
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  info: { padding: 16, gap: 6 },
  title: { fontSize: 18, fontWeight: '700' },
  description: { fontSize: 13, color: '#666', lineHeight: 20 },
  errorText: { color: '#FF3B30' },
  riveContainer: {
    height: 200, backgroundColor: '#f0f0f0',
    justifyContent: 'center', alignItems: 'center',
  },
  rive: { width: '100%', height: '100%' },
  logContainer: {
    flex: 1, margin: 16, backgroundColor: '#1a1a2e',
    borderRadius: 10, padding: 12,
  },
  logTitle: {
    color: '#888', fontSize: 12, fontWeight: '600',
    textTransform: 'uppercase', marginBottom: 8,
  },
  logPlaceholder: { color: '#666', fontSize: 12, fontFamily: 'monospace' },
  logEntry: { color: '#FF6B6B', fontSize: 11, fontFamily: 'monospace' },
});
```

</details>

### CODE REVIEW

File: src/hooks/useRiveProperty.ts [hunk 1]
```diff
@@ -86,15 +86,11 @@ export function useRiveProperty<P extends ViewModelProperty, T>(
...
+  // Set the value of the property (no-op if property isn't available yet)
   const setPropertyValue = useCallback(
     (valueOrUpdater: T | ((prevValue: T | undefined) => T)) => {
       if (!property) {
-        setError(
-          new Error(
-            `Cannot set value for property "${path}" because it was not found. Your view model instance may be undefined, or the path may be incorrect.`
-          )
-        );
+        return;
```
Comment (HayesGordon) [inline src/hooks/useRiveProperty.ts:93]: What about the scenario where the property is in fact invalid?

Comment (mfazekas) [reply src/hooks/useRiveProperty.ts:93]: > What about the scenario where the property is in fact invalid?

There is an useEffect on line 63 covering that. 

https://github.com/rive-app/rive-nitro-react-native/blob/4a5af1ba7c10d669b534dd1609f14526a291912a/src/hooks/useRiveProperty.ts#L63-L69

And I've added a test case covering this:
https://github.com/rive-app/rive-nitro-react-native/blob/4a5af1ba7c10d669b534dd1609f14526a291912a/src/hooks/__tests__/useRiveProperty.test.ts#L86-L98
